### PR TITLE
fix: search highlight is hard to read

### PR DESCRIPTION
**Pull request by xuanduc987**
## Before

image

## After

image

### CODE REVIEW

**Comment by adrian5** [comment]
Yes, that certainly isn't how it's supposed to look. The highlight is set to be a plain fg/bg inversion, which looks like this on my system:

search-hl

Do you use a plugin that might override the search highlight? I don't know where that bright yellow in your **Before** screenshot comes from, it could well be a fallback to vim defaults.

What output does `:hi Search` give you?

**Comment by xuanduc987** [comment]
Yes, because the default color scheme is 
```
:hi Search
Search         xxx term=reverse ctermbg=11 guibg=Yellow
```
thus, after combine with the value in this colorschem it become like this
```                                                                          
:hi Search                                                                                                      
Search         xxx term=reverse cterm=reverse ctermbg=11 gui=reverse  
```

**Comment by adrian5** [comment]
Which vim version are you using? My daily driver is nvim but I tried two GUIs, Neovide and gVim and couldn't reproduce your problem.

My colorscheme clears bg values unless they're set:

* 256-color mode → clears `ctermbg`
   ```viml
   :hi Search
   Search         xxx cterm=reverse guifg=Black guibg=Yellow
   "                                              ↑ ignored in 256-color
   ```
* truecolor mode (**you**) → clears `guibg`
   ```viml
   :hi Search
   Search         xxx cterm=reverse ctermfg=0 ctermbg=11 gui=reverse
   "                                             ↑ ignored in truecolor
   ```

That should ensure that there's no default yellow background to be "reversed".

You can confirm if that's the case by doing another search and then running `:hi Search ctermbg=Red` (should see *no change*) and `:hi Search guibg=Red` (foreground should *change*).

---

I wonder if you're running into the following issue (`:h hl-normal`):

```viml
NOTE: When using reverse video ("gvim -fg white -bg black"), the default value
of 'background' will not be set until the GUI window is opened, which is after
reading the |gvimrc|.  This will cause the wrong default highlighting to be
used.  To set the default value of 'background' before switching on
highlighting, include the ":gui" command in the |gvimrc|: >

   :gui		" open window and set default for 'background'
   :syntax on	" start highlighting, use 'background' to set colors

NOTE: Using ":gui" in the |gvimrc| means that "gvim -f" won't start in the
foreground!  Use ":gui -f" then.
```

**Comment by xuanduc987** [comment]
I'm using vim 8.2.1058 with `termguicolors` on in the terminal, not using gVim.
Seems like when there are no gui fg/bg setting, vim fallbacks to using cterm colors: https://github.com/vim/vim/commit/d4fc577e60d325777d38c00bd78fb9a32c7b1dfa

**Comment by adrian5** [comment]
Interesting! The changes in that patch may indeed be the culprit.  I've tried a recent vim 8.2 (after the patch) and can reproduce your issue there.

Looking at the code, I think the condition should be satisfied if I any `gui` color is set. Since the `Search` foreground is always "black" (oceanic bg color), it should be fine to permanently set `guibg` without breaking the inverted look, which I'd like to keep.

Assuming you're still using vim-plug, could you try the following:

```viml
Plug 'adrian5/oceanic-next-vim', { 'branch': 'dev' }
```

...then run `:PlugInstall` or `:PlugUpdate`, and tell me if that fixes the yellow text? Thanks!

**Comment by xuanduc987** [comment]
Thank you very much, the dev branch works perfectly.
I will close this PR

**Comment by adrian5** [comment]
Thank you Duc for the report, without your help I couldn't have figured it out so easily. I've pushed the fix to the master branch.

**Pull request closed without merging**
